version: '3.9'

services:
  web:
    ports:
      - "5678:5678"
      - "8000:8000"
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "manage.py", "runserver", "--nothreading", "--noreload", "0.0.0.0:8000"]
