# Generated by Django 4.0.6 on 2022-07-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director_movie'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='actors',
        ),
        migrations.AlterModelTable(
            name='director',
            table='directors',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
