# Generated by Django 4.0.6 on 2022-07-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_actor_table_alter_director_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='photo',
            field=models.ImageField(null=True, upload_to='directors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'G - General Audiences'), ('PG', 'PG - Parental Guidance Suggesteds'), ('PG-13', 'PG-13 - Parents Strongly Cautioned'), ('R', 'R - Restricted'), ('NC-17', 'NC-17 – Adults Only')], max_length=10),
        ),
    ]
