# Generated by Django 4.1 on 2022-08-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_review_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
