# Generated by Django 4.1 on 2022-08-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_movie_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="director",
            options={"verbose_name": "director", "verbose_name_plural": "directors"},
        ),
        migrations.AlterField(
            model_name="director",
            name="bio",
            field=models.TextField(null=True, verbose_name="bio"),
        ),
        migrations.AlterField(
            model_name="director",
            name="birthdate",
            field=models.DateField(null=True, verbose_name="birthdate"),
        ),
        migrations.AlterField(
            model_name="director",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="director",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="director",
            name="photo",
            field=models.ImageField(
                null=True, upload_to="directors", verbose_name="photo"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.director",
                verbose_name="director",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
    ]
