# Generated by Django 4.1.1 on 2022-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_genre_movie_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
