# Generated by Django 4.1.1 on 2022-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_movie_seats_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="price",
            field=models.IntegerField(default=10),
        ),
    ]
