# Generated by Django 4.1.1 on 2022-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_remove_purchase_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
